# fly.toml app configuration file generated for rasende2-api on 2023-05-06T01:18:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rasende2-api"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[mounts]
source = "rasende2_data"
destination = "/data"

[env]
PORT = "8080"
APP_ENV = "production"
SEARCH_INDEX_PATH = "/data/bleve_v2"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true

[checks]
[checks.alive]
type = "tcp"
interval = "15s"
timeout = "2s"
grace_period = "5s"

[metrics]
port = 9091
path = "/metrics"
