// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dao

import (
	"database/sql"
	"time"
)

type Cache struct {
	K         string      `json:"k"`
	V         string      `json:"v"`
	ExpiresAt interface{} `json:"expires_at"`
}

type FakeNews struct {
	SiteName    string         `json:"site_name"`
	Title       string         `json:"title"`
	Content     string         `json:"content"`
	Published   sql.NullTime   `json:"published"`
	SiteID      sql.NullInt64  `json:"site_id"`
	ImgUrl      sql.NullString `json:"img_url"`
	Highlighted bool           `json:"highlighted"`
	Votes       int64          `json:"votes"`
}

type MagicLink struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    int64     `json:"user_id"`
	OtpHash   string    `json:"otp_hash"`
	LinkCode  string    `json:"link_code"`
	ExpiresAt time.Time `json:"expires_at"`
}

type RssItem struct {
	ItemID     string         `json:"item_id"`
	SiteName   string         `json:"site_name"`
	Title      string         `json:"title"`
	Content    sql.NullString `json:"content"`
	Link       sql.NullString `json:"link"`
	Published  sql.NullTime   `json:"published"`
	InsertedAt sql.NullTime   `json:"inserted_at"`
	SiteID     sql.NullInt64  `json:"site_id"`
}

type SiteCount struct {
	SiteID       int64         `json:"site_id"`
	ArticleCount sql.NullInt64 `json:"article_count"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID             int64          `json:"id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	Email          string         `json:"email"`
	EmailConfirmed bool           `json:"email_confirmed"`
	PasswordHash   sql.NullString `json:"password_hash"`
	IsAdmin        bool           `json:"is_admin"`
}
